import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Nexttypewind</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section className="flex bg-scroll items-center justify-center bg-[url('../public/tech-banner.jpg')] h-[850px] bg-center bg-cover">
        <div>
        <h1 className="text-4xl text-white uppercase">Your tech solution</h1>
        </div>
      </section>
    </div>
  )
}

export default Home
